# Site settings
baseurl: https://blessb15.github.io/ExpressItPromos
title: ExPress It Promotional Products
description: >
  A hosted markdown blog with intuitive online editing. BowTie makes it easy to build sites, blogs, or static apps that you can hand off to clients.

email: expressitpromos@gmail.com
phone: (503)703-9436

logourl: /img/logo.png

author: Blake Bless

author_thumbnail:

# Theme additions - please update the default values if you intend to use these variables

google_analytics_id:  # Your google analytics ID (e.g. 'UA-XXXXXXXX-X')

google_api_key: 'AIzaSyBVJLhULkSOJYrDdHjBIsyYw8PBWAsXujo' # Your Google API key for Maps

theme:
  # Company contact info
  contact:
    company:  ExpressIt Promotional
    address:  18120 SE Blanton St
    city:     Milwaukie
    state:    OR
    zip:      97222
    country:  USA
    phone:    503-703-9436
    latlng:   45.391906,-122.616275 # (e.g. '45.391906,-122.616275')
    twitter:  twitter               # (e.g. 'twitter')
    facebook: facebook              # (e.g. 'facebook')
    github:                         # (e.g. 'github')
    instagram:                      # (e.g. 'instagram')
    flickr:                         # (e.g. 'groups/2772799@N24/')
    linkedin:                       # (e.g. 'company/linkedin')
    youtube:                        # (e.g. 'channel/UCovWO5keLOLcLu8WdO-ABJw')


  disqus_id:   bowtieexample        # From your Disqus account (e.g. 'bowtieexample')

  addthis_id:                       # From your Add This account (e.g. 'ra-00000a0a00a00aaa')

# Permalinks
permalink:           /:categories/:title/
relative_permalinks: false

gems: [jekyll-paginate]

# Pagination config
paginate: 5
paginate_path: /page/:num

# Jekyll build/resource locations

# source:  .
# destination: ./_site
# plugins_dir: null
# layouts_dir: ./_layouts
# data_dir:    ./_data
# includes_dir: ./_includes

# Jekyll Handling Reading
include:    [] # Specify files to be included in build that may be otherwise ignored (e.g. '[.htaccess]')

keep_files: [] # Files/Folders located inside the ./_site folder to be retained on build (e.g.'[.git, .svn]')

# Files/Folders to be excluded from generated '_site' folder
exclude:
  - .gitignore
  - .sass-cache

# define collection objects
collections:
  authors:
    output: false
  team:
    output: false
  sections:
    output: false
